# Label classifier (dSprites): data collection

**Author**: Maleakhi A. Wijaya  
**Description**: This notebook contains code used to collect experimentation data. We compare the performance of methods discussed in Rabanset et al. against our proposed CBSD method.

In [31]:
# Load utilities functions
%run ../../scripts/dsprites_utils.py
%run ../../scripts/shift_applicator.py
%run ../../scripts/shift_dimensionality_reductor.py
%run ../../scripts/constants.py
%run ../../scripts/experiment_utils.py
%run ../../scripts/shift_statistical_test.py

In [23]:
# Remove warnings
import warnings
warnings.filterwarnings('ignore')

## Load dataset

In [6]:
SEED = 20
np.random.seed(SEED)
tf.random.set_seed(SEED)

In [7]:
path = "../../data/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz"
X_train, X_test, y_train, y_test, c_train, c_test = load_dsprites(path, 100000, train_size=0.85, class_index=1)
n_classes_shape = 3

# Split training into validation set as well 
X_train, X_valid = X_train[:70000], X_train[70000:]
y_train, y_valid = y_train[:70000], y_train[70000:]
c_train, c_valid = c_train[:70000], c_train[70000:]

Training samples: 85000
Testing samples: 15000


In [8]:
# Reshape to appropriate shift input
# It is noteworthy that for efficiency, we represent the images as only 2 dimension
# when we preprocessing (number of instances/ batch size * flatten size).
# When visualising back the image, we need to reshape it back to the original dimension
ORIGINAL_SHAPE = X_test.shape[1:] # constant hold the image original shape
X_test_flatten = deepcopy(X_test.reshape(X_test.shape[0], -1))
X_train_flatten = deepcopy(X_train.reshape(X_train.shape[0], -1))
X_valid_flatten = deepcopy(X_valid.reshape(X_valid.shape[0], -1))

## Dimensionality reduction

We implemented various dimensionality reduction methods, amounting to:
- End to end model (label classifiers/ BBSD)
- Concept bottleneck model (CBSD)
- Trained and untrained autoencoders (TAE and UAE)
- Principal component analysis (PCA)
- Sparse random projection (SRP)

### End-to-end model

In [9]:
path = "../../models/end_to_end_dsprites"
# For training and saving
# histories, end_to_end_model = end_to_end_neural_network(n_classes_shape, Dataset.DSPRITES, 
#                          X_train, y_train, X_valid, y_valid,
#                          path)

# For loading
end_to_end_model = tf.keras.models.load_model(path)

In [58]:
# Evaluate model
y_pred = end_to_end_model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4935
           1       1.00      1.00      1.00      5051
           2       1.00      1.00      1.00      5014

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000



### Concept bottleneck model

**Input to Concept**

In [19]:
path = "../../models/multitask_dsprites"
# For training and saving
# histories, mt_model = multitask_model(Dataset.DSPRITES,
#                                             X_train, c_train,
#                                             X_valid, c_valid)

# For loading
mt_model = tf.keras.models.load_model(path)

In [20]:
# Evaluate model
for i, pred in enumerate(mt_model.predict(X_test)):
    print("*"*20, f"Model: {DSPRITES_CONCEPT_NAMES[i]}", "*"*20)
    c_truth = c_test[:, i]
    c_pred = np.argmax(pred, axis=1)
    
    print(classification_report(c_truth, c_pred))
    print("\n\n")

******************** Model: color ********************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15000

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000




******************** Model: shape ********************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5091
           1       1.00      1.00      1.00      5017
           2       1.00      1.00      1.00      4892

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000




******************** Model: scale ********************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2476
           1       1.00      1.00      1.00      2536
           2

**Concept to Output**

In [24]:
# Build and train model. For simplicity, we used logistic regression
# although can be substituted using other model.
com = LogisticRegression()
com.fit(c_train, y_train)

LogisticRegression()

In [25]:
y_test_pred = com.predict(c_test)
print(classification_report(y_test_pred, y_test))
print(confusion_matrix(y_test_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5091
           1       1.00      1.00      1.00      5017
           2       1.00      1.00      1.00      4892

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000

[[5091    0    0]
 [   0 5017    0]
 [   0    0 4892]]


### Principal component analysis

In [27]:
pca, n_components = principal_components_analysis(X_train_flatten)
print(f"The number of components to explain 80% of variance is {n_components}.")

The number of components to explain 80% of variance is 42.


### Sparse random projection

In [28]:
srp, n_components = sparse_random_projection(X_train_flatten)
print(f"The number of components to explain 80% of variance is {n_components}.")

The number of components to explain 80% of variance is 42.


### Autoencoder

In [ ]:
# The following are path to untrained and trained autoencoders
# (only the encoder)
path_uae = "../../models/uae_dsprites"
path_tae = "../../models/tae_dsprites"

# (both encoder and decoder)
path_full_uae = "../../models/uae_full_dsprites"
path_full_tae = "../../models/tae_full_dsprites"

# Train and save untrained autoencoder
u_encoder, u_autoenc = autoencoder(Dataset.DSPRITES, 
                                   X_train_flatten, X_valid_flatten,
                                  ORIGINAL_SHAPE, train=False)
u_encoder.save(path_uae)
u_autoenc.save(path_full_uae)

# Train and save trained autoencoder
encoder, autoenc = autoencoder(Dataset.DSPRITES,
                               X_train_flatten, X_valid_flatten,
                              ORIGINAL_SHAPE, train=True)
encoder.save(path_tae)
autoenc.save(path_full_tae)

INFO:tensorflow:Assets written to: ../../models/uae_dsprites/assets
INFO:tensorflow:Assets written to: ../../models/uae_full_dsprites/assets
Epoch 1/200
547/547 [==============================] - 68s 122ms/step - loss: 0.1729 - val_loss: 0.0205
Epoch 2/200
547/547 [==============================] - 67s 122ms/step - loss: 0.0197 - val_loss: 0.0178
Epoch 3/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0175 - val_loss: 0.0165
Epoch 4/200
547/547 [==============================] - 66s 121ms/step - loss: 0.0162 - val_loss: 0.0154
Epoch 5/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0153 - val_loss: 0.0146
Epoch 6/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0144 - val_loss: 0.0139
Epoch 7/200
547/547 [==============================] - 67s 122ms/step - loss: 0.0138 - val_loss: 0.0134
Epoch 8/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0134 - val_loss: 0.0131
Epoch 9/200
547/547 [======

Epoch 78/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0081 - val_loss: 0.0080
Epoch 79/200
547/547 [==============================] - 67s 122ms/step - loss: 0.0081 - val_loss: 0.0080
Epoch 80/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0080 - val_loss: 0.0080
Epoch 81/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0080 - val_loss: 0.0079
Epoch 82/200
547/547 [==============================] - 67s 122ms/step - loss: 0.0080 - val_loss: 0.0080
Epoch 83/200
547/547 [==============================] - 66s 120ms/step - loss: 0.0080 - val_loss: 0.0079
Epoch 84/200
547/547 [==============================] - 67s 122ms/step - loss: 0.0080 - val_loss: 0.0079
Epoch 85/200
547/547 [==============================] - 67s 123ms/step - loss: 0.0080 - val_loss: 0.0079
Epoch 86/200
547/547 [==============================] - 68s 124ms/step - loss: 0.0079 - val_loss: 0.0078
Epoch 87/200
547/547 [==============================] -